apiVersion: v1
kind: Service
metadata:
  name: wym-dvm-be
  labels:
    app: wym-dvm-be
spec:
  type: NodePort
  selector:
    app: wym-dvm-be
  ports:
  - name: http
    nodePort: 30371
    port: 8081
    targetPort: 8081
    protocol: TCP
