apiVersion: v1
kind: Service
metadata:
  name: wym-dvm-fe
  labels:
    app: wym-dvm-fe
spec:
  type: NodePort
  selector:
    app: wym-dvm-fe
  ports:
  - name: http
    nodePort: 30372
    port: 80
    targetPort: 80
    protocol: TCP
